"""o

Revision ID: cc9165be90df
Revises: 
Create Date: 2024-09-13 15:59:47.532112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9165be90df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viagem',
    sa.Column('id_pacote', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('preco', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.PrimaryKeyConstraint('id_pacote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem')
    # ### end Alembic commands ###
